doctrine:
  orm:
    auto_mapping: true
    mappings:
      zentlix_menu_menu:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/vendor/zentlix/menu-bundle/src/Domain/Menu/Entity'
        prefix: Zentlix\MenuBundle\Domain\Menu\Entity